name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: myacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: myacr.azurecr.io/my-nodejs-app:latest

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
