name: CI/CD

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: myazureregistry.azurecr.io/node-app:latest
        login-server: myazureregistry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Cluster Name and IP Address
      id: set-cluster-name-ip
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          if [ "${{ github.event.inputs.branch }}" == "main" ]; then
            echo "::set-output name=cluster-name::main-cluster"
            echo "::set-output name=cluster-ip::10.10.10.1"  # Example IP Address for main cluster
            echo "::set-output name=resource-group::main-aks-resource-group"
          else
            echo "::set-output name=cluster-name::develop-cluster"
            echo "::set-output name=cluster-ip::10.10.10.2"  # Example IP Address for develop cluster
            echo "::set-output name=resource-group::develop-aks-resource-group"
          fi
        else
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=cluster-name::main-cluster"
            echo "::set-output name=cluster-ip::10.10.10.1"  # Example IP Address for main cluster
            echo "::set-output name=resource-group::main-aks-resource-group"
          fi
        fi

    - name: Azure AKS Set Context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ steps.set-cluster-name-ip.outputs.cluster-name }}
        resource-group: ${{ steps.set-cluster-name-ip.outputs.resource-group }}

    - name: Deploy Node App to AKS
      run: |
        kubectl apply -f kubernetes/node-deployment.yaml
        echo "Application deployed to AKS Cluster: ${{ steps.set-cluster-name-ip.outputs.cluster-name }}"
        echo "AKS Cluster IP Address: ${{ steps.set-cluster-name-ip.outputs.cluster-ip }}"





# name: CI/CD

# on:
#   push:
#     branches:
#       - master
#       - develop

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
      
#     - name: Set up Docker Buildx #for different os architecture 
#       uses: docker/setup-buildx-action@v1
      
#     - name: Login to Azure Container Registry
#       uses: azure/docker-login@v1
#       with:
#         login-server: myacr.azurecr.io
#         username: ${{ secrets.ACR_USERNAME }}
#         password: ${{ secrets.ACR_PASSWORD }}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./Dockerfile
#         push: true
#         tags: acr.azurecr.io/my-nodejs-app:latest

#     - name: Deploy to AKS
#       uses: Azure/k8s-deploy@v1
#       with:
#         kubeconfig: ${{ secrets.KUBE_CONFIG }}
#         manifests: |
#           k8s/deployment.yaml
#           k8s/service.yaml
